services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      #- "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "8081:80"
    volumes:
      - "./config/pgadmin-config:/var/lib/pgadmin:rw"
volumes:
  postgres-data:
  pgadmin: